<?php

/**
 * @file
 * Main functions of the module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\owntracks\Entity\OwnTracksLocationInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function owntracks_entity_extra_field_info() {
  $fields['owntracks_location']['owntracks_location']['display']['map'] = [
    'label' => t('Map'),
    'description' => t('Display a map with a location marker.'),
    'weight' => -10,
    'visible' => TRUE,
  ];

  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function owntracks_owntracks_location_view(array &$build, OwnTracksLocationInterface $owntracks_location, EntityViewDisplayInterface $display) {
  if ($display->getComponent('map')) {
    $build['map'] = [
      '#theme' => 'owntracks_map',
      '#track' => [$owntracks_location->getLocation()],
    ];
  }
}

/**
 * Implements hook_requirements().
 */
function owntracks_requirements($phase) {
  $owntracks_map_configured = FALSE;

  return [
    'owntracks' => [
      'title' => 'OwnTracks Map Configuration',
      'value' => $owntracks_map_configured ? t('Configured') : t('Not configured'),
      'severity' => $owntracks_map_configured ? REQUIREMENT_OK : REQUIREMENT_ERROR,
      'description' => t('OwnTracks Map is not configured. <a href=":url">Add configuration</a>', [':url' => \Drupal::url('owntracks.map_settings')]),
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function owntracks_theme($existing, $type, $theme, $path) {
  return [
    'owntracks_location' => [
      'render element' => 'content',
    ],
    'owntracks_map' => [
      'file' => 'owntracks.theme.inc',
      'variables' => [
        'attributes' => [],
        'track' => [],
      ],
    ],
  ];
}
