<?php

/**
 * @file
 * Main functions of the module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\owntracks\Entity\OwnTracksLocationInterface;
use Drupal\owntracks\Entity\OwnTracksTransitionInterface;
use Drupal\owntracks\Entity\OwnTracksWaypointInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function owntracks_entity_extra_field_info() {
  $fields['owntracks_location']['owntracks_location']['display']['map'] = [
    'label' => t('Map'),
    'description' => t('Display a map with a location marker.'),
    'weight' => -10,
    'visible' => TRUE,
  ];

  $fields['owntracks_transition']['owntracks_transition']['display']['map'] = [
    'label' => t('Map'),
    'description' => t('Display a map with a transition marker.'),
    'weight' => -10,
    'visible' => TRUE,
  ];

  $fields['owntracks_waypoint']['owntracks_waypoint']['display']['map'] = [
    'label' => t('Map'),
    'description' => t('Display a map with a waypoint marker.'),
    'weight' => -10,
    'visible' => TRUE,
  ];

  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function owntracks_owntracks_location_view(array &$build, OwnTracksLocationInterface $owntracks_location, EntityViewDisplayInterface $display) {
  if ($display->getComponent('map')) {
    $build['map'] = [
      '#theme' => 'owntracks_map',
      '#track' => [$owntracks_location->getLocation()],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function owntracks_owntracks_transition_view(array &$build, OwnTracksTransitionInterface $owntracks_transition, EntityViewDisplayInterface $display) {
  if ($display->getComponent('map')) {
    $build['map'] = [
      '#theme' => 'owntracks_map',
      '#track' => [$owntracks_transition->getLocation()],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function owntracks_owntracks_waypoint_view(array &$build, OwnTracksWaypointInterface $owntracks_waypoint, EntityViewDisplayInterface $display) {
  if ($display->getComponent('map')) {
    $build['map'] = [
      '#theme' => 'owntracks_map',
      '#track' => [$owntracks_waypoint->getLocation()],
    ];
  }
}

/**
 * Implements hook_theme().
 */
function owntracks_theme($existing, $type, $theme, $path) {
  return [
    'owntracks_location' => [
      'render element' => 'content',
    ],
    'owntracks_transition' => [
      'render element' => 'content',
    ],
    'owntracks_waypoint' => [
      'render element' => 'content',
    ],
    'owntracks_map' => [
      'file' => 'owntracks.theme.inc',
      'variables' => [
        'attributes' => [],
        'track' => [],
      ],
    ],
  ];
}
